# Go
# Build your Go application.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/go

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/deislabs/duffle' # Path to the module's code

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    make bootstrap build
    make build-release
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'
# Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(modulePath)/bin'
    contents: '**' 
    targetFolder: '$(build.artifactStagingDirectory)'
# GitHub Release
- task: GithubRelease@0
  displayName: Create GitHub Release  
  inputs:
    gitHubConnection: 'Release Pipeline'
    repositoryName: $(Build.Repository.Name)
    action: 'create' 
    target: '$(build.sourceVersion)' 
    assets: '$(build.artifactStagingDirectory)/*'
    isDraft: true 
    isPreRelease: true 
    addChangeLog: true 